apiVersion: v1
kind: Service
metadata:
  name: incident-guard-ai-service
spec:
  selector:
    app: incident-guard-ai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer